# automatically generated by the FlatBuffers compiler, do not modify

# namespace: kfs

class AxiomKind(object):
    NONE = 0
    SubClassOf = 1
    EquivalentToIntersection = 2
    SubClassOfExistential = 3
    DisjointClasses = 4
    ClassAssertion = 5
