# automatically generated by the FlatBuffers compiler, do not modify

# namespace: kfs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Axiom(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Axiom()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAxiom(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def AxiomBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x46\x53\x30", size_prefixed=size_prefixed)

    # Axiom
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Axiom
    def KindType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Axiom
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def AxiomStart(builder):
    builder.StartObject(2)

def Start(builder):
    AxiomStart(builder)

def AxiomAddKindType(builder, kindType):
    builder.PrependUint8Slot(0, kindType, 0)

def AddKindType(builder, kindType):
    AxiomAddKindType(builder, kindType)

def AxiomAddKind(builder, kind):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(kind), 0)

def AddKind(builder, kind):
    AxiomAddKind(builder, kind)

def AxiomEnd(builder):
    return builder.EndObject()

def End(builder):
    return AxiomEnd(builder)
