# automatically generated by the FlatBuffers compiler, do not modify

# namespace: kfs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ClassAssertion(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClassAssertion()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClassAssertion(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ClassAssertionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x46\x53\x30", size_prefixed=size_prefixed)

    # ClassAssertion
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ClassAssertion
    def Cls(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ClassAssertion
    def Individual(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ClassAssertionStart(builder):
    builder.StartObject(2)

def Start(builder):
    ClassAssertionStart(builder)

def ClassAssertionAddCls(builder, cls):
    builder.PrependUint32Slot(0, cls, 0)

def AddCls(builder, cls):
    ClassAssertionAddCls(builder, cls)

def ClassAssertionAddIndividual(builder, individual):
    builder.PrependUint32Slot(1, individual, 0)

def AddIndividual(builder, individual):
    ClassAssertionAddIndividual(builder, individual)

def ClassAssertionEnd(builder):
    return builder.EndObject()

def End(builder):
    return ClassAssertionEnd(builder)
