# automatically generated by the FlatBuffers compiler, do not modify

# namespace: kfs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DisjointClasses(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DisjointClasses()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDisjointClasses(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DisjointClassesBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x46\x53\x30", size_prefixed=size_prefixed)

    # DisjointClasses
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DisjointClasses
    def A(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # DisjointClasses
    def B(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def DisjointClassesStart(builder):
    builder.StartObject(2)

def Start(builder):
    DisjointClassesStart(builder)

def DisjointClassesAddA(builder, a):
    builder.PrependUint32Slot(0, a, 0)

def AddA(builder, a):
    DisjointClassesAddA(builder, a)

def DisjointClassesAddB(builder, b):
    builder.PrependUint32Slot(1, b, 0)

def AddB(builder, b):
    DisjointClassesAddB(builder, b)

def DisjointClassesEnd(builder):
    return builder.EndObject()

def End(builder):
    return DisjointClassesEnd(builder)
