# automatically generated by the FlatBuffers compiler, do not modify

# namespace: kfs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EquivalentToIntersection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EquivalentToIntersection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEquivalentToIntersection(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def EquivalentToIntersectionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x46\x53\x30", size_prefixed=size_prefixed)

    # EquivalentToIntersection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EquivalentToIntersection
    def Lhs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EquivalentToIntersection
    def Parts(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # EquivalentToIntersection
    def PartsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # EquivalentToIntersection
    def PartsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EquivalentToIntersection
    def PartsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def EquivalentToIntersectionStart(builder):
    builder.StartObject(2)

def Start(builder):
    EquivalentToIntersectionStart(builder)

def EquivalentToIntersectionAddLhs(builder, lhs):
    builder.PrependUint32Slot(0, lhs, 0)

def AddLhs(builder, lhs):
    EquivalentToIntersectionAddLhs(builder, lhs)

def EquivalentToIntersectionAddParts(builder, parts):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(parts), 0)

def AddParts(builder, parts):
    EquivalentToIntersectionAddParts(builder, parts)

def EquivalentToIntersectionStartPartsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartPartsVector(builder, numElems):
    return EquivalentToIntersectionStartPartsVector(builder, numElems)

def EquivalentToIntersectionEnd(builder):
    return builder.EndObject()

def End(builder):
    return EquivalentToIntersectionEnd(builder)
