# automatically generated by the FlatBuffers compiler, do not modify

# namespace: kfs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FactStream(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FactStream()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFactStream(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FactStreamBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x46\x53\x30", size_prefixed=size_prefixed)

    # FactStream
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FactStream
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 1

    # interned entity names; axioms reference by index
    # FactStream
    def Names(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # FactStream
    def NamesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FactStream
    def NamesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # FactStream
    def Axioms(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from kvasir.kfs.Axiom import Axiom
            obj = Axiom()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FactStream
    def AxiomsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FactStream
    def AxiomsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # provenance of the emitting artifact (e.g. "sdg-ontology@<git-sha>")
    # FactStream
    def Source(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def FactStreamStart(builder):
    builder.StartObject(4)

def Start(builder):
    FactStreamStart(builder)

def FactStreamAddVersion(builder, version):
    builder.PrependUint16Slot(0, version, 1)

def AddVersion(builder, version):
    FactStreamAddVersion(builder, version)

def FactStreamAddNames(builder, names):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(names), 0)

def AddNames(builder, names):
    FactStreamAddNames(builder, names)

def FactStreamStartNamesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNamesVector(builder, numElems):
    return FactStreamStartNamesVector(builder, numElems)

def FactStreamAddAxioms(builder, axioms):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(axioms), 0)

def AddAxioms(builder, axioms):
    FactStreamAddAxioms(builder, axioms)

def FactStreamStartAxiomsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAxiomsVector(builder, numElems):
    return FactStreamStartAxiomsVector(builder, numElems)

def FactStreamAddSource(builder, source):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(source), 0)

def AddSource(builder, source):
    FactStreamAddSource(builder, source)

def FactStreamEnd(builder):
    return builder.EndObject()

def End(builder):
    return FactStreamEnd(builder)
