# automatically generated by the FlatBuffers compiler, do not modify

# namespace: kfs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SubClassOf(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SubClassOf()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSubClassOf(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SubClassOfBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x46\x53\x30", size_prefixed=size_prefixed)

    # SubClassOf
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SubClassOf
    def Sub(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SubClassOf
    def Sup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def SubClassOfStart(builder):
    builder.StartObject(2)

def Start(builder):
    SubClassOfStart(builder)

def SubClassOfAddSub(builder, sub):
    builder.PrependUint32Slot(0, sub, 0)

def AddSub(builder, sub):
    SubClassOfAddSub(builder, sub)

def SubClassOfAddSup(builder, sup):
    builder.PrependUint32Slot(1, sup, 0)

def AddSup(builder, sup):
    SubClassOfAddSup(builder, sup)

def SubClassOfEnd(builder):
    return builder.EndObject()

def End(builder):
    return SubClassOfEnd(builder)
