# automatically generated by the FlatBuffers compiler, do not modify

# namespace: kfs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SubClassOfExistential(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SubClassOfExistential()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSubClassOfExistential(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SubClassOfExistentialBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4B\x46\x53\x30", size_prefixed=size_prefixed)

    # SubClassOfExistential
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SubClassOfExistential
    def Sub(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SubClassOfExistential
    def Role(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SubClassOfExistential
    def Filler(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def SubClassOfExistentialStart(builder):
    builder.StartObject(3)

def Start(builder):
    SubClassOfExistentialStart(builder)

def SubClassOfExistentialAddSub(builder, sub):
    builder.PrependUint32Slot(0, sub, 0)

def AddSub(builder, sub):
    SubClassOfExistentialAddSub(builder, sub)

def SubClassOfExistentialAddRole(builder, role):
    builder.PrependUint32Slot(1, role, 0)

def AddRole(builder, role):
    SubClassOfExistentialAddRole(builder, role)

def SubClassOfExistentialAddFiller(builder, filler):
    builder.PrependUint32Slot(2, filler, 0)

def AddFiller(builder, filler):
    SubClassOfExistentialAddFiller(builder, filler)

def SubClassOfExistentialEnd(builder):
    return builder.EndObject()

def End(builder):
    return SubClassOfExistentialEnd(builder)
